# Generated by Django 5.1.2 on 2024-11-06 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_caducidad', models.DateField()),
                ('puntaje_asignado', models.PositiveIntegerField()),
                ('puntaje_utilizado', models.PositiveIntegerField(default=0)),
                ('saldo_puntos', models.PositiveIntegerField(editable=False)),
                ('monto_operacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas_puntos', to='clientes.cliente')),
            ],
        ),
    ]
