# Generated by Django 5.1.2 on 2024-11-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsaPuntos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsapuntos',
            name='saldo_puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
