# Generated by Django 5.1.3 on 2024-12-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("niveles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("duracion_dias", models.IntegerField(editable=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("descuento", "Descuento"),
                            ("bonificacion", "Bonificacion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bonificacion", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nivel",
                        to="niveles.niveles",
                    ),
                ),
            ],
        ),
    ]
