# Generated by Django 5.1.3 on 2024-12-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beneficios", "0001_initial"),
        ("niveles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficios",
            name="nombre",
        ),
        migrations.AddField(
            model_name="beneficios",
            name="descuento",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="beneficios",
            name="nivel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="niveles",
                to="niveles.niveles",
            ),
        ),
    ]
