# Generated by Django 5.1.2 on 2024-12-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('edad_minima', models.PositiveIntegerField(default=0)),
                ('edad_maxima', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentacion.criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segmentacion.criterio')),
            ],
        ),
    ]
