# Generated by Django 5.1.2 on 2024-11-10 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
        ('conceptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_utilizado', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptos.concepto')),
            ],
        ),
    ]
