# Generated by Django 5.1.2 on 2024-11-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reglas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limite_inferior", models.IntegerField()),
                ("limite_superior", models.IntegerField()),
                ("monto", models.IntegerField(default=0)),
            ],
        ),
    ]
