# Generated by Django 5.1.2 on 2024-11-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.CharField(max_length=50),
        ),
    ]
