# Generated by Django 5.1.2 on 2024-11-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolsaPuntos', '0001_initial'),
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoPuntosCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_utilizado', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('concepto_uso', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_puntos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='UsoPuntosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_utilizado', models.PositiveIntegerField()),
                ('bolsa_puntos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='bolsaPuntos.bolsapuntos')),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='usoPuntos.usopuntoscabecera')),
            ],
        ),
    ]
